---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance1
    hostname: instance1
    image: samueldebruyn/debian-git
    networks:
      - name: testnet
  - name: instance2
    hostname: instance2
    image: smheidrich/debian-git-sshd
    networks:
      - name: testnet
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/playbook.yml
      x: ["ANSIBLE0006", "ANSIBLE0012"]
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
