---
- name: Locally generate SSH key that will be used for testing
  hosts: localhost
  tasks:
    - tempfile:
        state: directory
      register: tmp_ssh_key
    - shell: >
        cat /dev/zero |
        ssh-keygen -q -N "" -f {{ tmp_ssh_key.path | quote }}/id_rsa
- name: Copy generated SSH key to ~/.ssh on instance1
  hosts: instance1
  tasks:
    - file:
        path: '~/.ssh/'
        state: directory
    - copy:
        src: "{{ hostvars['localhost']['tmp_ssh_key'].path | quote }}/id_rsa"
        dest: "~/.ssh/id_rsa"
    - copy:
        src: "{{ hostvars['localhost']['tmp_ssh_key'].path | quote }}/id_rsa"
        dest: "~/.ssh/id_rsa.pub"
- name: Make generated SSH key authorized on instance2
  hosts: instance2
  tasks:
    - authorized_key:
        user: '{{ ansible_user_id }}'
        state: present
        key: >
          {{
            lookup(
              'file',
              hostvars['localhost']['tmp_ssh_key'].path+'/id_rsa.pub'
            )
          }}
- name: Start sshd on instance2
  hosts: instance2
  become: yes
  tasks:
    - service:
        name: ssh
        state: started
- name: Set up simulated source git repo on instance1
  hosts: instance1
  tasks:
    - shell: |
        mkdir ~/test_repo
        cd ~/test_repo
        git init
        git config user.name 'testuser'
        git config user.email 'testuser@example.net'
        echo "hello world" > some_file
        git add some_file
        git commit -a -m "Initial"
- name: "Simple test of our role: push to instance2"
  hosts: instance2
  roles:
    - role: git_remote_from_local
      vars:
        src: ~/test_repo
        dest: /tmp/test_repo  # TODO ???
        push: yes
        src_host: instance1
