---
- name: "Simple test of our role: push to instance2"
  hosts: instance2
  roles:
    - role: git_remote_from_local
      vars:
        src: ~/test_repo
        dest: /tmp/test_repo  # TODO ???
        push: yes
        src_host: instance1
