---
- name: "Install git (TODO: this should probably go somewhere else)"
  hosts: all
  become: true
  tasks:
    - yum:
        name: git
        state: installed
- name: Set up simulated source git repo on localhost
  hosts: localhost
  tasks:
    - tempfile:
        state: directory
      register: repo_tmp
    - shell: |
        cd {{ repo_tmp.path | quote }}
        git init
        git config user.name 'testuser'
        git config user.email 'testuser@example.net'
        echo "hello world" > some_file
        git add some_file
        git commit -a -m "Initial"
- name: "Simple test of our role: push to instance2"
  hosts: instance2
  roles:
    - role: git_remote_from_local
      vars:
        src: "{{ repo_tmp.path }}"
        dest: /tmp/test_repo  # TODO ???
        push: yes
